apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  startingDeadlineSeconds: 15
  schedule: 0 0 1 * *
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: django-clearsessions
            image: django_app:latest
            imagePullPolicy: IfNotPresent
            command:
            - ./manage.py
            - clearsessions
            envFrom:
            - secretRef:
                name: secrets